### PR TITLE
Remove old FP client file no longer used and delete npyscreen dependency

### PR DESCRIPTION
**Pull request by ajgdls**
Reference issue #189

### CODE REVIEW

**Comment by GDYendell** [comment]
In #189 you suggested removing the entire directory. Is there any reason not to do that?
If not you should probably at least delete the `__main__.py`, which imports and runs this client.

**Comment by ajgdls** [comment]
I had suggested we remove the entire directory, but I felt that specifically for this PR I only wanted to clean out the npyscreen reference.  However you are right there is no reason not to remove the entire directory so I'll add it to this PR.

**Comment by ajgdls** [comment]
Good spot, removed those scripts.

**Comment by ajgdls** [comment]
@GDYendell squashed and merged.

**Pull request merged**
