### PR TITLE
Checked FileWriterPlugin is expecting frames before starting writing

### PR DESCRIPTION
**Pull request by MattTaylorDLS**
BC-499

### CODE REVIEW

**Comment by GDYendell** [comment]
This looks good, but it would be nice to make it clear that there the two cases for starting writing. If totalFrames == 0 we want to write regardless because we are in free running mode and if not then we are only writing if we are expecting > 0 frames, based on rank.

You could split the if into 3 blocks, but a comment for each would probably be clear enough.

**Comment by MattTaylorDLS** [comment]
OK Maybe i'll add some comments. Think it'd be better not to have three parts of the 'if' blocks when two of them are doing the same thing

**Comment by MattTaylorDLS** [comment]
Yeah ok

**Comment by MattTaylorDLS** [comment]
@timcnicholls, you happy for me to merge this?

**Pull request merged**
