### PR TITLE
Separate FrameDecoder out into shared library

### PR DESCRIPTION
**Pull request by timcnicholls**
Fixes problem with detector-specific decoder test apps having to
have access to main frameReceiver source.

### CODE REVIEW

**Comment by ajgdls** [comment]
@GDYendell @MattTaylorDLS I would like to get this PR in as soon as possible please, so I can restore the makefiles in my detector project.

**Comment by timcnicholls** [comment]
Thanks @ajgdls . Suggest if we haven't had objections from @GDYendell or @MattTaylorDLS by the end of the day we merge it.

**Comment by ajgdls** [comment]
@timcnicholls do you mind if I merge this?

**Comment by ajgdls** [comment]
Oh never mind sorry you've already done it!!

**Comment by timcnicholls** [comment]
@ajgdls Yeah, just got back to office after interviewing. Now merged

**Comment by ajgdls** [comment]
Thanks.

**Pull request merged**
