### PR TITLE
Backtrace

### PR DESCRIPTION
**Pull request by ajgdls**
Catching crashes and giving the application the best chance to print out a trace.
Applications register with the handler and then a mangled stack trace is printed out if a crash occurs.
The trace can easily be de-mangled on line so I have left them mangled.  If we try to de-mangle them in the handler then we could easily lock up as memory allocations are required; if the cause of the crash involves memory it might result in nothing printed at all.  Better to get a mangled trace which can be de-mangled at any point in the future (in my opinion).
As this is the last chance of any output from the application I'm also printing to stderr to keep it simple.
However, I'm open to comments regarding this...

### CODE REVIEW

**Comment by ajgdls** [comment]
`./prefix/bin/frameProcessor 
5 [0x7f8dfdf71760] INFO FP.App null - frameProcessor version 0-6-1-dirty starting up
9 [0x7f8dfdf71760] INFO FP.FrameProcessorController null - Running frame processor
Caught signal 11 (SIGSEGV)
stack trace:
./prefix/bin/frameProcessor(_ZN8OdinData17print_stack_traceEP8_IO_FILEj+0x87)[0x486c13]
./prefix/bin/frameProcessor(_ZN8OdinData13abort_handlerEiP7siginfoPv+0xbb)[0x486d30]
/lib64/libpthread.so.0[0x37b300f7e0]
/lib64/libpthread.so.0(pthread_cond_wait+0xcc)[0x37b300b68c]
./prefix/bin/frameProcessor(_ZN5boost18condition_variable4waitERNS_11unique_lockINS_5mutexEEE+0x6b)[0x465187]
./prefix/bin/frameProcessor(_ZN14FrameProcessor24FrameProcessorController15waitForShutdownEv+0x43)[0x4612b5]
./prefix/bin/frameProcessor(_ZN14FrameProcessor24FrameProcessorController3runEv+0x11d)[0x460809]
./prefix/bin/frameProcessor(main+0x1188)[0x492ddd]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x37b2c1ed1d]
./prefix/bin/frameProcessor[0x459d29]
terminate called after throwing an instance of 'OdinData::IpcReactorException'
  what():  IpcReactor error while polling: Context was terminated
Caught signal 6 (SIGABRT)
stack trace:
./prefix/bin/frameProcessor(_ZN8OdinData17print_stack_traceEP8_IO_FILEj+0x87)[0x486c13]
./prefix/bin/frameProcessor(_ZN8OdinData13abort_handlerEiP7siginfoPv+0xbb)[0x486d30]
/lib64/libpthread.so.0[0x37b300f7e0]
/lib64/libc.so.6(gsignal+0x35)[0x37b2c32495]
/lib64/libc.so.6(abort+0x175)[0x37b2c33c75]
/usr/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x12d)[0x37b94bea8d]
/usr/lib64/libstdc++.so.6[0x37b94bcbe6]
/usr/lib64/libstdc++.so.6[0x37b94bcc13]
/usr/lib64/libstdc++.so.6[0x37b94bcd32]
/home/gnx91527/work/odin-data/prefix/lib/libOdinData.so(_ZN8OdinData10IpcReactor3runEv+0x397)[0x7f8dfe70776f]
./prefix/bin/frameProcessor(_ZN14FrameProcessor24FrameProcessorController13runIpcServiceEv+0x2d7)[0x463091]
./prefix/bin/frameProcessor(_ZNK5boost4_mfi3mf0IvN14FrameProcessor24FrameProcessorControllerEEclEPS3_+0x59)[0x47e0cd]
./prefix/bin/frameProcessor(_ZN5boost3_bi5list1INS0_5valueIPN14FrameProcessor24FrameProcessorControllerEEEEclINS_4_mfi3mf0IvS4_EENS0_5list0EEEvNS0_4typeIvEERT_RT0_i+0x4a)[0x479fcc]
./prefix/bin/frameProcessor(_ZN5boost3_bi6bind_tIvNS_4_mfi3mf0IvN14FrameProcessor24FrameProcessorControllerEEENS0_5list1INS0_5valueIPS5_EEEEEclEv+0x3f)[0x4795d5]
./prefix/bin/frameProcessor(_ZN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf0IvN14FrameProcessor24FrameProcessorControllerEEENS2_5list1INS2_5valueIPS7_EEEEEEE3runEv+0x1e)[0x47f50e]
/dls_sw/prod/tools/RHEL6-x86_64/boost/1-48-0dls1/prefix/lib/libboost_thread.so.1.48.0(+0xebd3)[0x7f8dff746bd3]
/lib64/libpthread.so.0[0x37b3007aa1]
/lib64/libc.so.6(clone+0x6d)[0x37b2ce8bdd]
`

**Comment by ajgdls** [comment]
And after running it through demangler.com

`./prefix/bin/frameProcessor 
5 [0x7f8dfdf71760] INFO FP.App null - frameProcessor version 0-6-1-dirty starting up
9 [0x7f8dfdf71760] INFO FP.FrameProcessorController null - Running frame processor
Caught signal 11 (SIGSEGV)
stack trace:
./prefix/bin/frameProcessor(OdinData::print_stack_trace(_IO_FILE*, unsigned int) 0x87)[0x486c13]
./prefix/bin/frameProcessor(OdinData::abort_handler(int, siginfo*, void*) 0xbb)[0x486d30]
/lib64/libpthread.so.0[0x37b300f7e0]
/lib64/libpthread.so.0(pthread_cond_wait 0xcc)[0x37b300b68c]
./prefix/bin/frameProcessor(boost::condition_variable::wait(boost::unique_lock<boost::mutex>&) 0x6b)[0x465187]
./prefix/bin/frameProcessor(FrameProcessor::FrameProcessorController::waitForShutdown() 0x43)[0x4612b5]
./prefix/bin/frameProcessor(FrameProcessor::FrameProcessorController::run() 0x11d)[0x460809]
./prefix/bin/frameProcessor(main 0x1188)[0x492ddd]
/lib64/libc.so.6(__libc_start_main 0xfd)[0x37b2c1ed1d]
./prefix/bin/frameProcessor[0x459d29]
terminate called after throwing an instance of 'OdinData::IpcReactorException'
  what():  IpcReactor error while polling: Context was terminated
Caught signal 6 (SIGABRT)
stack trace:
./prefix/bin/frameProcessor(OdinData::print_stack_trace(_IO_FILE*, unsigned int) 0x87)[0x486c13]
./prefix/bin/frameProcessor(OdinData::abort_handler(int, siginfo*, void*) 0xbb)[0x486d30]
/lib64/libpthread.so.0[0x37b300f7e0]
/lib64/libc.so.6(gsignal 0x35)[0x37b2c32495]
/lib64/libc.so.6(abort 0x175)[0x37b2c33c75]
/usr/lib64/libstdc  .so.6(__gnu_cxx::__verbose_terminate_handler() 0x12d)[0x37b94bea8d]
/usr/lib64/libstdc  .so.6[0x37b94bcbe6]
/usr/lib64/libstdc  .so.6[0x37b94bcc13]
/usr/lib64/libstdc  .so.6[0x37b94bcd32]
/home/gnx91527/work/odin-data/prefix/lib/libOdinData.so(OdinData::IpcReactor::run() 0x397)[0x7f8dfe70776f]
./prefix/bin/frameProcessor(FrameProcessor::FrameProcessorController::runIpcService() 0x2d7)[0x463091]
./prefix/bin/frameProcessor(boost::_mfi::mf0<void, FrameProcessor::FrameProcessorController>::operator()(FrameProcessor::FrameProcessorController*) const 0x59)[0x47e0cd]
./prefix/bin/frameProcessor(void boost::_bi::list1<boost::_bi::value<FrameProcessor::FrameProcessorController*> >::operator()<boost::_mfi::mf0<void, FrameProcessor::FrameProcessorController>, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf0<void, FrameProcessor::FrameProcessorController>&, boost::_bi::list0&, int) 0x4a)[0x479fcc]
./prefix/bin/frameProcessor(boost::_bi::bind_t<void, boost::_mfi::mf0<void, FrameProcessor::FrameProcessorController>, boost::_bi::list1<boost::_bi::value<FrameProcessor::FrameProcessorController*> > >::operator()() 0x3f)[0x4795d5]
./prefix/bin/frameProcessor(boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, FrameProcessor::FrameProcessorController>, boost::_bi::list1<boost::_bi::value<FrameProcessor::FrameProcessorController*> > > >::run() 0x1e)[0x47f50e]
/dls_sw/prod/tools/RHEL6-x86_64/boost/1-48-0dls1/prefix/lib/libboost_thread.so.1.48.0( 0xebd3)[0x7f8dff746bd3]
/lib64/libpthread.so.0[0x37b3007aa1]
/lib64/libc.so.6(clone 0x6d)[0x37b2ce8bdd]`

**Comment by ajgdls** [comment]
@ulrikpedersen that is correct during a crash it's possible that all of the logging is non-functional, memory corrupted etc.  To give this last ditch attempt to catch all the best chance to produce something you would want to use the simplest mechanism for outputting.  I guess we could try to log properly as well after dumping to stdout/stderr.

**Comment by ulrikpedersen** [comment]
> To give this last ditch attempt to catch all the best chance to produce something you would want to use the simplest mechanism for outputting. I guess we could try to log properly as well after dumping to stdout/stderr.

Yes, that would be helpful.

Have you considered using low-level syslog calls? I expect those are fairly primitive and might work in crashing scenarios. Syslog can be redirected in many different ways by external processes.

**Pull request merged**
