### PR TITLE
Update FrameProcessor README

### PR DESCRIPTION
**Pull request by GDYendell**
I have updated the docs in the Design.md for the latest code (mostly name changes). The only thing is the classes diagram is still wrong. I have also merged the Design into the README so that it all displays nicely on the GitHub page.

Having this up to date will make it much easier to explain to people how it all works.

(If you view the commits individually, the diff will be much more useful)

### CODE REVIEW

**Comment by GDYendell** [comment]
Is the fr setup in master now?

Also, how did you make the class diagram / how would I update it?

**Comment by ajgdls** [comment]
Yes I believe it went in on 17th August PR #52 . I've noticed it running on my LATRD application recently as you get a delayed (1 second I think) notification message once the shared memory handshake has completed.

For the diagram:
https://yuml.me/diagram/scruffy/class/draw

**Comment by ajgdls** [comment]
By the way this PR isn't passing tests, is that because the branch is behind master?

**Comment by GDYendell** [comment]
Fixed it... (whoops)

**Comment by GDYendell** [comment]
Do we want to keep mentions of specific detectors out of the docs? (For the plugins on the class diagram)

**Comment by ajgdls** [comment]
I guess in an ideal world we create an example detector that lives in the odin-data module and can be used as a template.  I would say yes keep specific detectors out of the docs here.

**Comment by GDYendell** [comment]
frameprocessor class hierarchy

**Comment by ajgdls** [comment]
Yes I think that looks great.

**Comment by GDYendell** [comment]
Now edited your one directly I will go with this

**Pull request merged**
