### PR TITLE
Docs, CI build and CLI interface improvements

### PR DESCRIPTION
**Pull request by GDYendell**
Waiting on #301 

This change aims to make it easier for new developers to get started using odin-data. There are a few unrelated parts:
- Docs with doxygen generated API
- Fixing / simplifying the dummy example so it is can be run easily and reliably
- Fix system tests that run in CI
- Tear out a lot of frameProcessor CLI options superceded by the json config

Note that this branch requires the changes in #301, so includes those commits for now.

The docs are still very much a work in progress, but this adds the foundation to start adding to them. The keys things are:
- There are a lot of warnings from the [doxygen build](https://github.com/odin-detector/odin-data/actions/runs/3150170490/jobs/5122646711#step:4:429) about undocumented code
- There should be more prose-with-API docs for the most important things to know
  - I started with the obvious classes, but probably not everything and I haven't written much description on how to use them.
- `Using the Python Tools` is very out of date, but I have left because it is probably better to have it than not.
- Code Climate is not providing any coverage information - I notice we use codecov for odin-control, which might be better
- Diagrams to aid with descriptive parts
  - I would like to create some Excalidraw diagrams because they can be checked in to git and easily edited with a freely available web editor

### CODE REVIEW

**Comment by GDYendell** [comment]
@timcnicholls could you enable the docs build under `Settings > Pages > Build and Deployment`? Hopefully then it will run the build step. I am not sure if it will actually publish them until they are built on master.

**Comment by timcnicholls** [comment]
> @timcnicholls could you enable the docs build under `Settings > Pages > Build and Deployment`? Hopefully then it will run the build step. I am not sure if it will actually publish them until they are built on master.

@GDYendell  Sure. Which mode do you want? Deploy from branch or Github Actions?

**Comment by GDYendell** [comment]
I think just Deploy from branch and then gh-pages. It uses [this action](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token) to deploy it.

**Comment by GDYendell** [comment]
Check for more docs content:
- https://github.com/stfc-aeg/odin-workshop
- https://github.com/odin-detector/odin-detector.github.io/tree/wip

**Comment by GDYendell** [comment]
This PR fixes a few existing issues. Check through and link them here.

**Comment by GDYendell** [comment]
Update references to SharedMemoryParser. Replaced with SharedMemoryManager in 9fc3b93c754ca2e24e274bd94bd9d3b889b1a2c4

**Comment by GDYendell** [comment]
Check whether odin-data compiles OK with std=cxx11 compile flag

**Comment by GDYendell** [comment]
Superceded by #317, #318, #314

**Pull request closed without merging**
