### PR TITLE
print JSON parse error on app start-up

### PR DESCRIPTION
**Pull request by skyfrench**
Issue #186

### CODE REVIEW

**Comment by skyfrench** [comment]
> Is the limit a character limit, so for example you will either print up to the previous and next line or up to +- 15 characters (whichever is minimum)?

Yes. I wanted to protect against somebody having a JSON config file formatted all on one line, for example. Without the character limit it worked nicely printing the whole line; but I had nicely formatted JSON files to test with ...

**Comment by ajgdls** [comment]
OK I see.  That looks fine, do you think +- 15 characters will normally get the whole line - difficult question to answer I guess (would it work for the current Excalibur config files)?
Are you able to get the line number also by counting \n characters?

**Comment by skyfrench** [comment]
The character limit of 15 wouldn't capture the decoder_path in very many cases I don't suppose, but perhaps most other things?

Current example print out looks like this (when typo of ";" not ":"):

11:22:28,038 FR.App         ERROR - Frame receiver run failed: Parsing JSON configuration failed at offset 24: Missing a colon after a name of object member.     "decoder_type"; "Excalibur",

I could add line number. 

What would the most useful content of the message be?

**Comment by ajgdls** [comment]
Most of what you have looks fine.  I think a line number would be good for finding quickly the issue within the file.
You could update the message to be
Parse JSON failed at line [n]: Missing a colon after a name of object member. "decoder_type"; "Excalibur",

**Comment by ajgdls** [comment]
Great!  It looks like you might need to re-base this branch to be able to get it merged due to conflicts in the CMakeLists.txt.

**Pull request merged**
