### PR TITLE
Separated file writer plugin registration call into a new cpp file.

### PR DESCRIPTION
**Pull request by ajgdls**
This allows the file writer plugin to be subclassed by specific detectors.
Updated CMakeLists.txt files.

### CODE REVIEW

**Comment by ajgdls** [comment]
Yes I think @GDYendell is working on the Travis build already as part of another PR.  Is this the same error that you noticed Gary?

**Comment by GDYendell** [comment]
I have not seen that error on my SWMR branch, though I do have a different problem there, I'm not sure what this is. Though, I notice that the path we are trying to curl for hdf5 does not exist: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/

Maybe they have moved things around?

**Comment by ulrikpedersen** [comment]
The travis build of hdf5 is mentioned on #53 as well. Also #53 requires updating hdf5 to 1.10.1  which can be found here: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz

**Comment by ajgdls** [comment]
@GDYendell are you happy to approve this PR now?

**Comment by ajgdls** [comment]
OK @timcnicholls I'm going to merge this if you are OK with that.

**Pull request merged**
